# Site settings
title: Cayle Sharrock
description: >- # this means to ignore newlines until "baseurl:"
  Blockchain and Rust Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# --------------------------------------------------- THEME settings ---------------------------------------------------
footer_text: '© 2024 Cayle Sharrock'
admin_name: 'Cayle Sharrock'
google_analytics:

#### CV data_dir
curriculum_vitae:
  name: Cayle Sharrock
  profile_pic: img/profile-animex256.jpg
  socials:
    - name: CjS77
      url: https://github.com/CjS77
      icon: fa-github
    - name: cjsharrock
      url: https://www.linkedin.com/in/cjsharrock/
      icon: fa-linkedin
  info:
    residence: Portugal
    citizenship: South African
    email: cayle.sharrock@gmail.com

hero_buttons:
  - name: Experience
    url: '#experience'
    icon: fa-briefcase
    section: experience
  - name: Projects
    url: '#projects'
    icon: fa-code
    section: projects
  - name: Publications
    url: '#publications'
    icon: fa-book
    section: publications
  - name: Videos
    url: '#videos'
    icon: fa-video
    section: videos
